"use client"

import React, { createContext, useContext, useState, useEffect } from 'react'

export type Language = 'en' | 'fil'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation dictionary
const translations = {
  en: {
    // Navigation
    'nav.overview': 'Overview',
    'nav.dashboard': 'Dashboard',
    'nav.employee_management': 'Employee Management',
    'nav.all_employees': 'All Employees',
    'nav.attendance': 'Attendance',
    'nav.attendance_logs': 'Attendance Logs',
    'nav.reports_analytics': 'Reports & Analytics',
    'nav.reports': 'Reports',
    'nav.system_management': 'System Management',
    'nav.verification': 'Verification',
    'nav.audit_trail': 'Audit Trail',
    'nav.notifications': 'Notifications',
    'nav.communication': 'Communication',
    'nav.email_notifications': 'Email Notifications',
    'nav.administration': 'Administration',
    'nav.system_settings': 'System Settings',
    'nav.user_management': 'User Management',
    'nav.dark_mode': 'Dark Mode',
    
    // Dashboard
    'dashboard.welcome': 'Welcome!',
    'dashboard.overview': 'Dashboard Overview',
    'dashboard.subtitle': 'Real-time attendance monitoring and system insights for STI College',
    'dashboard.system_online': 'System Online',
    'dashboard.export_report': 'Export Report',
    'dashboard.todays_attendance': "Today's Attendance",
    'dashboard.real_time_status': 'Real-time attendance status',
    'dashboard.present': 'Present',
    'dashboard.late': 'Late',
    'dashboard.absent': 'Absent',
    'dashboard.on_leave': 'On Leave',
    'dashboard.performance_metrics': 'Performance Metrics',
    'dashboard.this_month_stats': "This month's statistics",
    'dashboard.attendance_rate': 'Attendance Rate',
    'dashboard.punctuality_rate': 'Punctuality Rate',
    'dashboard.avg_hours_day': 'Avg. Hours/Day',
    'dashboard.overtime_hours': 'Overtime Hours',
    'dashboard.recent_alerts': 'Recent Alerts',
    'dashboard.system_notifications': 'System notifications',
    'dashboard.no_alerts': 'No alerts at this time',
    'dashboard.quick_actions': 'Quick Actions',
    'dashboard.frequent_tasks': 'Frequently used administrative tasks',
    'dashboard.add_employee': 'Add Employee',
    'dashboard.manual_entry': 'Manual Entry',
    'dashboard.generate_report': 'Generate Report',
    'dashboard.send_notification': 'Send Notification',
    
    // Common
    'common.loading': 'Loading...',
    'common.search': 'Search',
    'common.search_placeholder': 'Search employees, pages, logs...',
    'common.online': 'Online',
    'common.offline': 'Offline',
    'common.refresh': 'Refresh',
    'common.notifications': 'Notifications',
    'common.new_notifications': 'new notifications',
    'common.view_all': 'View all notifications',
    'common.calendar': 'Calendar',
    'common.open_calendar': 'Open Calendar',
    
    // Landing Page
    'landing.system_overview': 'RFID Attendance Monitoring System',
    'landing.learn_more_about': 'How RAMS System Works',
    'landing.learn_more_description': 'Discover how our RFID Attendance Monitoring System revolutionizes employee tracking with cutting-edge technology and seamless integration. Our advanced system provides real-time monitoring, comprehensive reporting, and secure access control.',
    'landing.rfid_scanning': 'RFID card scanning for attendance',
    'landing.automatic_logging': 'Automatic time-in and time-out logging',
    'landing.reports_generation': 'Employee attendance reports generation',
    'landing.learn_more_button': 'Learn More About RAMS',
    'landing.featured': 'Featured',
    'landing.sign_in': 'Sign In to RAMS',
    'landing.featured_sti': 'STI College Santa Rosa',
    'landing.featured_sti_desc': 'Leading in Technology Education',
    'landing.featured_rams': 'RAMS System',
    'landing.featured_rams_desc': 'Advanced Attendance Management',
    'landing.featured_rfid': 'RFID Technology',
    'landing.featured_rfid_desc': 'Contactless Attendance Tracking',
    'landing.featured_integration': 'RFID Integration',
    'landing.featured_integration_desc': 'Seamless System Integration',
    'landing.featured_monitoring': 'Real-time Monitoring',
    'landing.featured_monitoring_desc': 'Live Attendance Tracking',
    'landing.featured_reports': 'Generate Reports',
    'landing.featured_reports_desc': 'Comprehensive Data Analysis',
    'landing.featured_secure': 'Secure Access',
    'landing.featured_secure_desc': 'Protected System Access',
    
    // Login Page
    'login.email_address': 'Email Address',
    'login.email_placeholder': 'your.email@santarosa.sti.edu',
    'login.password': 'Password',
    'login.password_placeholder': 'Enter your password',
    'login.remember_me': 'Remember me',
    'login.sign_in': 'Sign In',
    'login.authenticating': 'Authenticating...',
    'login.invalid_credentials': 'Invalid credentials. Please check your email and password.',
    'login.scan_qr': 'Scan QR code or click it to open STIRams',
    'login.login_successful': 'Login Successful',
    'login.welcome_back': 'Welcome back, {name}!',
    
    // How RAMS Works Page
    'how.works_title': 'How RAMS Works',
    'how.works_description': 'Discover how our RFID Attendance Monitoring System revolutionizes employee tracking with cutting-edge technology and seamless integration.',
    'how.it_works_title': 'How It Works',
    'how.step1_number': '01',
    'how.step1_title': 'RFID Card Assignment',
    'how.step1_desc': 'Each employee receives a unique RFID card with encrypted identification data.',
    'how.step2_number': '02',
    'how.step2_title': 'Card Scanning',
    'how.step2_desc': 'Employees scan their RFID cards at designated readers to clock in/out.',
    'how.step3_number': '03',
    'how.step3_title': 'Data Processing',
    'how.step3_desc': 'The system processes attendance data and updates records in real-time.',
    'how.step4_number': '04',
    'how.step4_title': 'Report Generation',
    'how.step4_desc': 'Administrators can generate detailed reports and analytics instantly.',
    'how.key_features_title': 'Key Features',
    'how.feature1_title': 'Employee Management',
    'how.feature1_desc': 'Comprehensive employee database with RFID card assignment and profile management.',
    'how.feature2_title': 'Real-time Attendance',
    'how.feature2_desc': 'Instant attendance tracking with precise time stamps and location verification.',
    'how.feature3_title': 'Secure Access',
    'how.feature3_desc': 'Multi-level security with encrypted data transmission and secure authentication.',
    'how.feature4_title': 'Analytics & Reports',
    'how.feature4_desc': 'Generate detailed reports and analytics for attendance patterns and insights.',
    'how.feature5_title': 'Mobile Responsive',
    'how.feature5_desc': 'Access the system from any device with our responsive web interface.',
    'how.feature6_title': 'Cloud Integration',
    'how.feature6_desc': 'Seamless cloud synchronization with real-time data backup and recovery.',
    'how.dev_team_title': 'Meet Our Development Team',
    'how.ready_title': 'Ready to Get Started?',
    'how.ready_description': 'Experience the power of RFID-based attendance monitoring with RAMS.',
    'how.sign_in': 'Sign In to RAMS',
    'how.back_home': 'Back to Home',
    'how.back': 'Back',
    
    // Sidebar
    'sidebar.overview': 'Overview',
    'sidebar.dashboard': 'Dashboard',
    'sidebar.attendance': 'Attendance',
    'sidebar.calendar': 'Calendar',
    'sidebar.reports': 'Reports',
    'sidebar.management': 'Management',
    'sidebar.employees': 'Employees',
    'sidebar.users': 'Users',
    'sidebar.time_tracking': 'Time Tracking',
    'sidebar.email_notifications': 'Email Notifications',
    'sidebar.documents': 'Documents',
    'sidebar.system': 'System',
    'sidebar.notifications': 'Notifications',
    'sidebar.verification': 'Verification',
    'sidebar.audit_trail': 'Audit Trail',
    'sidebar.settings': 'Settings',
    'sidebar.security': 'Security',
    'sidebar.account_settings': 'Account Settings',
    'sidebar.sign_out': 'Sign Out',
    'sidebar.sti_college': 'STI College Santa Rosa',
    
    // Email Notifications Page
    'email.title': 'Email Notifications',
    'email.subtitle': 'Pick cutoff, choose recipients, and send a modern report email',
    'email.compose': 'Compose Report Email',
    'email.template': 'Template: Employee Report (fixed) • Database-backed preview',
    'email.cutoff_period': 'Cutoff Period',
    'email.cutoff_month': 'Cutoff Month',
    'email.start': 'Start',
    'email.end': 'End',
    'email.email_settings': 'Email Settings',
    'email.subject': 'Subject',
    'email.subject_placeholder': 'Attendance Report',
    'email.bulk_send': 'Bulk send to multiple employees',
    'email.select_employee': 'Select Employee',
    'email.bulk_selection': 'Bulk Selection',
    'email.selected': 'selected',
    'email.search_placeholder': 'Search name, email, or department...',
    'email.present': 'Present',
    'email.late': 'Late',
    'email.absent': 'Absent',
    'email.show_details': 'Show details',
    'email.hide_details': 'Hide details',
    'email.attendance_details': 'Attendance Details',
    'email.date': 'Date',
    'email.time_in': 'Time In',
    'email.time_out': 'Time Out',
    'email.status': 'Status',
    'email.sending': 'Sending...',
    'email.send_email': 'Send Email',
    'email.email_preview': 'Email Preview',
    'email.show': 'Show',
    'email.hide': 'Hide',
    'email.hey': 'Hi',
    'email.report_message': 'Please click the button below to view or download your Attendance Report for This Month.',
    'email.weekly_report': 'Weekly Report',
    'email.period': 'Period',
    'email.days_present': 'Days Present',
    'email.days_absent': 'Days Absent',
    'email.late_arrivals': 'Late Arrivals',
    'email.early_departures': 'Early Departures',
    'email.automated_email': 'This is an automated email from the STI College Santa Rosa RAMS System.',
    'email.rams_system': 'RAMS System',
    'email.noreply': 'noreply@santarosa.sti.edu',
    'email.emails_sent': 'Emails sent',
    'email.delivered': 'email(s) delivered.',
    'email.send_failed': 'Send failed',
    
    // Calendar Page
    'calendar.select_date': 'Select a date and manage your agenda.',
    'calendar.pick_date': 'Pick a date',
    'calendar.today_highlighted': 'Today is highlighted; navigate infinitely.',
    'calendar.agenda_for': 'Agenda for',
    'calendar.add': 'Add',
    'calendar.add_notes': 'Add notes for the selected day.',
    'calendar.placeholder': 'Type your agenda note...',
    'calendar.no_notes': 'No notes yet for this day.',
    'calendar.more': 'more',
    
    // Reports Page
    'reports.title': 'Reports & Analytics',
    'reports.subtitle': 'Comprehensive attendance reports and performance analytics',
    'reports.export_csv': 'Export CSV',
    'reports.refresh_data': 'Refresh Data',
    'reports.total_employees': 'Total Employees',
    'reports.active_workforce': 'Active workforce',
    'reports.present_today': 'Present Today',
    'reports.attendance': 'attendance',
    'reports.late_today': 'Late Today',
    'reports.need_attention': 'Need attention',
    'reports.absent_today': 'Absent Today',
    'reports.follow_up_required': 'Follow up required',
    'reports.daily_attendance': 'Daily Attendance Trend',
    'reports.last_7_days': 'Last 7 days attendance overview',
    'reports.department_performance': 'Department Performance',
    'reports.attendance_rates': 'Attendance rates by department',
    'reports.employee_performance': 'Employee Performance Report',
    'reports.detailed_stats': 'Detailed attendance statistics for all employees',
    'reports.all_employees': 'All Employees',
    'reports.department_summary': 'Department Summary',
    'reports.performance_overview': 'Performance overview by department',
    'reports.total_days': 'Total Days',
    'reports.attendance_rate': 'Attendance Rate',
    'reports.punctuality_rate': 'Punctuality Rate',
    'reports.error': 'Error',
    'reports.loading_error': 'Failed to load reports data',
    'reports.exported': 'Report Exported',
    'reports.downloaded': 'Attendance report has been downloaded as CSV file.',
    
    // Settings Page
    'settings.title': 'System Settings',
    'settings.subtitle': 'Configure system preferences, integrations, and security settings for RAMS',
    'settings.backup_now': 'Backup Now',
    'settings.saving': 'Saving...',
    'settings.save_settings': 'Save Settings',
    'settings.system_status': 'System Status',
    'settings.database': 'Database',
    'settings.connected': 'Connected',
    'settings.email_service': 'Email Service',
    'settings.active': 'Active',
    'settings.last_backup': 'Last Backup',
    'settings.general_system': 'General System Settings',
    'settings.general_description': 'Configure general system preferences and behavior',
    'settings.email_config': 'Email Configuration',
    'settings.email_description': 'Configure SMTP settings for email notifications',
    'settings.test_email': 'Test Email Connection',
    'settings.security_access': 'Security & Access Control',
    'settings.security_description': 'Configure security settings and access controls',
    'settings.two_factor': 'Two-Factor Authentication',
    'settings.require_2fa': 'Require 2FA for admin accounts',
    'settings.session_timeout': 'Session Timeout',
    'settings.auto_logout': 'Auto logout after inactivity',
    'settings.login_attempts': 'Login Attempts',
    'settings.max_failed': 'Max failed login attempts',
    'settings.ip_whitelist': 'IP Whitelist',
    'settings.restrict_access': 'Restrict access to specific IPs',
    'settings.authorized_users': 'Authorized Users',
    'settings.settings_saved': 'Settings Saved',
    'settings.settings_updated': 'System settings have been updated successfully.',
    'settings.connection_test': 'Connection Test',
    'settings.connection_completed': 'connection test completed successfully.',
    'settings.backup_completed': 'Backup Completed',
    'settings.backup_created': 'Database backup has been created successfully.',
    'settings.system': 'System',
    'settings.email': 'Email',
    'settings.security': 'Security',
    'settings.hourly': 'Hourly',
    'settings.daily': 'Daily',
    'settings.weekly': 'Weekly',
    'settings.monthly': 'Monthly',
    'settings.minutes': 'minutes',
    'settings.hour': 'hour',
    'settings.hours': 'hours',
    'settings.super_admin': 'Super Admin',
    'settings.admin': 'Admin',
    
    // Users Page
    'users.title': 'User Management',
    'users.disabled_notice': 'This User Management area is currently disabled.',
    'users.search_users': 'Search Users',
    'users.search_placeholder': 'Search by name or email...',
    'users.active': 'Active',
    'users.inactive': 'Inactive',
    'users.super_admin': 'Super Admin',
    'users.admin': 'Admin',
    'users.viewer': 'Viewer',
    
    // Attendance Page
    'attendance.title': 'Attendance Monitoring',
    'attendance.subtitle': 'Monitor and track employee attendance logs in real-time',
    'attendance.live_monitoring': 'Live Monitoring',
    'attendance.last_updated': 'Last updated',
    'attendance.refreshing': 'Refreshing...',
    'attendance.refresh_data': 'Refresh Data',
    'attendance.total_employees': 'Total Employees',
    'attendance.active_employees': 'Active employees',
    'attendance.on_time_today': 'On-Time Today',
    'attendance.late_today': 'Late Today',
    'attendance.requires_attention': 'Requires attention',
    'attendance.absent_today': 'Absent Today',
    'attendance.work_not_started': 'Work Has Not Started Yet',
    'attendance.need_followup': 'Need follow-up',
    'attendance.logs': 'Attendance Logs',
    'attendance.realtime': 'Real-time attendance monitoring and log management',
    'attendance.search_placeholder': 'Search by employee name, RFID, or department...',
    'attendance.include_absences': 'Include absences',
    'attendance.hide_not_started': 'Hide Work Has Not Started Yet',
    'attendance.sort_by': 'Sort by',
    'attendance.direction': 'Direction',
    'attendance.ascending': 'Ascending',
    'attendance.descending': 'Descending',
    'attendance.time': 'Time',
    'attendance.name': 'Name',
    'attendance.employee': 'Employee',
    'attendance.school_id': 'School ID',
    'attendance.department': 'Department',
    'attendance.log_type': 'Log Type',
    'attendance.date': 'Date',
    'attendance.status': 'Status',
    'attendance.notes': 'Notes',
    'attendance.all_statuses': 'All Statuses',
    'attendance.all_types': 'All Types',
    'attendance.all_staff': 'All Staff',
    'attendance.teaching': 'Teaching',
    'attendance.non_teaching': 'Non-Teaching',
    'attendance.no_logs': 'No attendance logs found. Logs will appear here when employees use their RFID cards.',
    'attendance.no_match': 'No logs match your current filters.',
    'attendance.page_of': 'Page',
    'attendance.of': 'of',
    'attendance.prev': 'Prev',
    'attendance.next': 'Next',
    'attendance.pick_date': 'Pick a date',
    'attendance.today': 'Today',
    'attendance.on_time': 'On-Time',
    'attendance.late': 'Late',
    'attendance.absent': 'Absent',
    'attendance.data_updated': 'Data Updated',
    'attendance.loaded_logs': 'Successfully loaded',
    'attendance.attendance_logs': 'attendance logs',
    'attendance.error': 'Error',
    'attendance.load_failed': 'Failed to load attendance data',
    'attendance.unknown_employee': 'Unknown Employee',
    'attendance.na': 'N/A',
    'attendance.logs_word': 'logs',
    
    // Employees Page
    'employees.title': 'Employee Management',
    'employees.subtitle': 'Manage all faculty members and non-teaching staff at STI College Santa Rosa',
    'employees.add_employee': 'Add Employee',
    'employees.total_employees': 'Total Employees',
    'employees.registered_employees': 'Registered employees',
    'employees.departments': 'Departments',
    'employees.across_departments': 'Across different departments',
    'employees.filter_search': 'Filter & Search Employees',
    'employees.search_placeholder': 'Search by name, ID, email, or RFID code...',
    'employees.all_departments': 'All Departments',
    'employees.all_statuses': 'All Statuses',
    'employees.employee_directory': 'Employee Directory',
    'employees.showing': 'Showing',
    'employees.of': 'of',
    'employees.employees': 'employees',
    'employees.name': 'Name',
    'employees.department_position': 'Department / Position',
    'employees.contact': 'Contact',
    'employees.rfid_schedule': 'RFID / Schedule',
    'employees.status': 'Status',
    'employees.work_status': 'Work Status',
    'employees.actions': 'Actions',
    'employees.view': 'View',
    'employees.edit': 'Edit',
    'employees.delete': 'Delete',
    'employees.active': 'Active',
    'employees.inactive': 'Inactive',
    'employees.regular': 'Regular',
    'employees.part_time': 'Part Time',
    'employees.part_time_full_load': 'Part Time Full Load',
    'employees.teaching': 'Teaching',
    'employees.non_teaching': 'Non-Teaching',
    
    // Verification Page
    'verification.title': 'Verification Requests',
    'verification.subtitle': 'Review and manage employee verification requests',
    'verification.pending': 'Pending',
    'verification.approved': 'Approved',
    'verification.rejected': 'Rejected',
    'verification.all_statuses': 'All Statuses',
    'verification.search_placeholder': 'Search by employee name or ID...',
    'verification.employee': 'Employee',
    'verification.request_type': 'Request Type',
    'verification.date_requested': 'Date Requested',
    'verification.status': 'Status',
    'verification.actions': 'Actions',
    'verification.approve': 'Approve',
    'verification.reject': 'Reject',
    'verification.view_details': 'View Details',
    'verification.no_requests': 'No verification requests found',
    'verification.filter_by_status': 'Filter by Status',
    
    // Audit Trail Page
    'audit.title': 'Audit Trail',
    'audit.subtitle': 'Track all system activities and changes',
    'audit.search_placeholder': 'Search by user, action, or description...',
    'audit.filter_by_action': 'Filter by Action',
    'audit.all_actions': 'All Actions',
    'audit.user': 'User',
    'audit.action': 'Action',
    'audit.description': 'Description',
    'audit.timestamp': 'Timestamp',
    'audit.details': 'Details',
    'audit.view_details': 'View Details',
    'audit.no_logs': 'No log trail entries found',
    'audit.clear_logs': 'Clear Log Trail',
    'audit.export_logs': 'Export Logs',
    'audit.refresh': 'Refresh',
  },
  fil: {
    // Navigation
    'nav.overview': 'Pangkalahatang Tanawin',
    'nav.dashboard': 'Dashboard',
    'nav.employee_management': 'Pamamahala ng mga Empleyado',
    'nav.all_employees': 'Lahat ng Empleyado',
    'nav.attendance': 'Pagdalo',
    'nav.attendance_logs': 'Mga Tala ng Pagdalo',
    'nav.reports_analytics': 'Mga Ulat at Pagsusuri',
    'nav.reports': 'Mga Ulat',
    'nav.system_management': 'Pamamahala ng Sistema',
    'nav.verification': 'Pagpapatunay',
    'nav.audit_trail': 'Tala ng Audit',
    'nav.notifications': 'Mga Abiso',
    'nav.communication': 'Komunikasyon',
    'nav.email_notifications': 'Mga Abiso sa Email',
    'nav.administration': 'Pangangasiwa',
    'nav.system_settings': 'Mga Setting ng Sistema',
    'nav.user_management': 'Pamamahala ng mga User',
    'nav.dark_mode': 'Madilim na Mode',
    
    // Dashboard
    'dashboard.welcome': 'Maligayang pagdating!',
    'dashboard.overview': 'Pangkalahatang Tanawin ng Dashboard',
    'dashboard.subtitle': 'Real-time na pagsubaybay sa pagdalo at mga insight ng sistema para sa STI College',
    'dashboard.system_online': 'Sistema Online',
    'dashboard.export_report': 'I-export ang Ulat',
    'dashboard.todays_attendance': 'Pagdalo ngayong Araw',
    'dashboard.real_time_status': 'Real-time na status ng pagdalo',
    'dashboard.present': 'Narito',
    'dashboard.late': 'Nahuli',
    'dashboard.absent': 'Wala',
    'dashboard.on_leave': 'Naka-leave',
    'dashboard.performance_metrics': 'Mga Sukat ng Pagganap',
    'dashboard.this_month_stats': 'Mga istatistika ng buwang ito',
    'dashboard.attendance_rate': 'Rate ng Pagdalo',
    'dashboard.punctuality_rate': 'Rate ng Puntualidad',
    'dashboard.avg_hours_day': 'Karaniwang Oras/Araw',
    'dashboard.overtime_hours': 'Mga Oras ng Overtime',
    'dashboard.recent_alerts': 'Mga Kamakailang Alerto',
    'dashboard.system_notifications': 'Mga abiso ng sistema',
    'dashboard.no_alerts': 'Walang alerto sa oras na ito',
    'dashboard.quick_actions': 'Mabilis na Aksyon',
    'dashboard.frequent_tasks': 'Madalas na ginagamit na mga gawain sa pangangasiwa',
    'dashboard.add_employee': 'Magdagdag ng Empleyado',
    'dashboard.manual_entry': 'Manual na Entry',
    'dashboard.generate_report': 'Gumawa ng Ulat',
    'dashboard.send_notification': 'Magpadala ng Abiso',
    
    // Common
    'common.loading': 'Naglo-load...',
    'common.search': 'Maghanap',
    'common.search_placeholder': 'Maghanap ng mga empleyado, pahina, tala...',
    'common.online': 'Online',
    'common.offline': 'Offline',
    'common.refresh': 'I-refresh',
    'common.notifications': 'Mga Abiso',
    'common.new_notifications': 'mga bagong abiso',
    'common.view_all': 'Tingnan ang lahat ng abiso',
    'common.calendar': 'Kalendaryo',
    'common.open_calendar': 'Buksan ang Kalendaryo',
    
    // Landing Page
    'landing.system_overview': 'RFID Attendance Monitoring System',
    'landing.learn_more_about': 'Paano Gumagana ang Sistema ng RAMS',
    'landing.learn_more_description': 'Alamin kung paano binabagong-bago ng aming RFID Attendance Monitoring System ang pagsusubaybay ng mga empleyado gamit ang pinakabagong teknolohiya at walang sawang integrasyon. Ang aming advanced na sistema ay nagbibigay ng real-time na pagsubaybay, malawak na pag-uulat, at secure na access control.',
    'landing.rfid_scanning': 'RFID card scanning para sa pagdalo',
    'landing.automatic_logging': 'Automatic na pag-log ng time-in at time-out',
    'landing.reports_generation': 'Pag-generate ng mga ulat ng pagdalo ng mga empleyado',
    'landing.learn_more_button': 'Matuto Pa Tungkol sa RAMS',
    'landing.featured': 'Featured',
    'landing.sign_in': 'Mag-sign In sa RAMS',
    'landing.featured_sti': 'STI College Santa Rosa',
    'landing.featured_sti_desc': 'Nangunguna sa Technology Education',
    'landing.featured_rams': 'Sistema ng RAMS',
    'landing.featured_rams_desc': 'Advanced na Pamamahala ng Pagdalo',
    'landing.featured_rfid': 'RFID Technology',
    'landing.featured_rfid_desc': 'Contactless na Pagsubaybay ng Pagdalo',
    'landing.featured_integration': 'RFID Integration',
    'landing.featured_integration_desc': 'Walang Sawang Integrasyon ng Sistema',
    'landing.featured_monitoring': 'Real-time na Pagsubaybay',
    'landing.featured_monitoring_desc': 'Live na Pagsubaybay ng Pagdalo',
    'landing.featured_reports': 'Gumawa ng mga Ulat',
    'landing.featured_reports_desc': 'Malawak na Pagsusuri ng Data',
    'landing.featured_secure': 'Secure na Access',
    'landing.featured_secure_desc': 'Protektadong Access sa Sistema',
    
    // Login Page
    'login.email_address': 'Email Address',
    'login.email_placeholder': 'your.email@santarosa.sti.edu',
    'login.password': 'Password',
    'login.password_placeholder': 'Ilagay ang iyong password',
    'login.remember_me': 'Tandaan mo ako',
    'login.sign_in': 'Mag-sign In',
    'login.authenticating': 'Nag-au-authenticate...',
    'login.invalid_credentials': 'Hindi wastong credentials. Paki-check ang iyong email at password.',
    'login.scan_qr': 'I-scan ang QR code o i-click ito para mabuksan ang STIRams',
    'login.login_successful': 'Matagumpay na Pag-login',
    'login.welcome_back': 'Maligayang pagbalik, {name}!',
    
    // How RAMS Works Page
    'how.works_title': 'Paano Gumagana ang RAMS',
    'how.works_description': 'Alamin kung paano binabagong-bago ng aming RFID Attendance Monitoring System ang pagsusubaybay ng mga empleyado gamit ang pinakabagong teknolohiya at walang sawang integrasyon.',
    'how.it_works_title': 'Paano Ito Gumagana',
    'how.step1_number': '01',
    'how.step1_title': 'RFID Card Assignment',
    'how.step1_desc': 'Bawat empleyado ay tumatanggap ng natatanging RFID card na may encrypted na identification data.',
    'how.step2_number': '02',
    'how.step2_title': 'Card Scanning',
    'how.step2_desc': 'Nag-iscan ang mga empleyado ng kanilang RFID cards sa mga itinalagang readers para mag-clock in/out.',
    'how.step3_number': '03',
    'how.step3_title': 'Data Processing',
    'how.step3_desc': 'Pinoproseso ng sistema ang attendance data at nagu-update ng mga records sa real-time.',
    'how.step4_number': '04',
    'how.step4_title': 'Report Generation',
    'how.step4_desc': 'Pwede gumawa ng mga detalyadong reports at analytics ang mga administrator agad-agad.',
    'how.key_features_title': 'Mga Pangunahing Features',
    'how.feature1_title': 'Pamamahala ng mga Empleyado',
    'how.feature1_desc': 'Malawak na database ng mga empleyado na may RFID card assignment at profile management.',
    'how.feature2_title': 'Real-time na Pagdalo',
    'how.feature2_desc': 'Instant na pagsubaybay ng pagdalo na may tumpak na time stamps at location verification.',
    'how.feature3_title': 'Secure na Access',
    'how.feature3_desc': 'Multi-level security na may encrypted data transmission at secure authentication.',
    'how.feature4_title': 'Analytics & Reports',
    'how.feature4_desc': 'Gumawa ng mga detalyadong reports at analytics para sa mga pattern ng pagdalo at insights.',
    'how.feature5_title': 'Mobile Responsive',
    'how.feature5_desc': 'I-access ang sistema mula sa anumang device gamit ang aming responsive web interface.',
    'how.feature6_title': 'Cloud Integration',
    'how.feature6_desc': 'Walang sawang cloud synchronization na may real-time data backup at recovery.',
    'how.dev_team_title': 'Kilalanin ang Aming Development Team',
    'how.ready_title': 'Handa na Ba Gumawa?',
    'how.ready_description': 'Maranasan ang kapangyarihan ng RFID-based attendance monitoring gamit ang RAMS.',
    'how.sign_in': 'Mag-sign In sa RAMS',
    'how.back_home': 'Bumalik sa Home',
    'how.back': 'Bumalik',
    
    // Sidebar
    'sidebar.overview': 'Pangkalahatang Tanawin',
    'sidebar.dashboard': 'Dashboard',
    'sidebar.attendance': 'Pagdalo',
    'sidebar.calendar': 'Kalendaryo',
    'sidebar.reports': 'Mga Ulat',
    'sidebar.management': 'Pamamahala',
    'sidebar.employees': 'Mga Empleyado',
    'sidebar.users': 'Mga User',
    'sidebar.time_tracking': 'Pagsusubaybay sa Oras',
    'sidebar.email_notifications': 'Mga Abiso sa Email',
    'sidebar.documents': 'Mga Dokumento',
    'sidebar.system': 'Sistema',
    'sidebar.notifications': 'Mga Abiso',
    'sidebar.verification': 'Pagpapatunay',
    'sidebar.audit_trail': 'Tala ng Audit',
    'sidebar.settings': 'Mga Setting',
    'sidebar.security': 'Security',
    'sidebar.account_settings': 'Mga Setting ng Account',
    'sidebar.sign_out': 'Mag-sign Out',
    'sidebar.sti_college': 'STI College Santa Rosa',
    
    // Email Notifications Page
    'email.title': 'Mga Abiso sa Email',
    'email.subtitle': 'Pumili ng cutoff, piliin ang mga recipients, at magpadala ng modern na report email',
    'email.compose': 'Gumawa ng Report Email',
    'email.template': 'Template: Employee Report (nakapirmi) • Database-backed preview',
    'email.cutoff_period': 'Panahon ng Cutoff',
    'email.cutoff_month': 'Buang Cutoff',
    'email.start': 'Simula',
    'email.end': 'Tapos',
    'email.email_settings': 'Mga Setting ng Email',
    'email.subject': 'Subject',
    'email.subject_placeholder': 'Ulat ng Pagdalo',
    'email.bulk_send': 'Bulk send sa maramihang empleyado',
    'email.select_employee': 'Pumili ng Empleyado',
    'email.bulk_selection': 'Maramihang Pagpili',
    'email.selected': 'napili',
    'email.search_placeholder': 'Maghanap ng pangalan, email, o department...',
    'email.present': 'Narito',
    'email.late': 'Nahuli',
    'email.absent': 'Wala',
    'email.show_details': 'Ipakita ang mga detalye',
    'email.hide_details': 'Itago ang mga detalye',
    'email.attendance_details': 'Mga Detalye ng Pagdalo',
    'email.date': 'Petsa',
    'email.time_in': 'Oras ng Pasok',
    'email.time_out': 'Oras ng Labas',
    'email.status': 'Status',
    'email.sending': 'Nagpapadala...',
    'email.send_email': 'Magpadala ng Email',
    'email.email_preview': 'Preview ng Email',
    'email.show': 'Ipakita',
    'email.hide': 'Itago',
    'email.hey': 'Kumusta',
    'email.report_message': 'Paki-click ang button sa ibaba para makita o i-download ang iyong Attendance Report para sa Buwan na Ito.',
    'email.weekly_report': 'Weekly Report',
    'email.period': 'Panahon',
    'email.days_present': 'Mga Araw na Narito',
    'email.days_absent': 'Mga Araw na Wala',
    'email.late_arrivals': 'Late Arrivals',
    'email.early_departures': 'Early Departures',
    'email.automated_email': 'Ito ay isang automated na email mula sa STI College Santa Rosa RAMS System.',
    'email.rams_system': 'RAMS System',
    'email.noreply': 'noreply@santarosa.sti.edu',
    'email.emails_sent': 'Naipadala ang mga email',
    'email.delivered': 'email(s) naipadala.',
    'email.send_failed': 'Nabigo ang pagpadala',
    
    // Calendar Page
    'calendar.select_date': 'Pumili ng petsa at pamahalaan ang iyong agenda.',
    'calendar.pick_date': 'Pumili ng petsa',
    'calendar.today_highlighted': 'Naka-highlight ang ngayon; mag-navigate nang walang hanggan.',
    'calendar.agenda_for': 'Agenda para sa',
    'calendar.add': 'Magdagdag',
    'calendar.add_notes': 'Magdagdag ng mga notes para sa napiling araw.',
    'calendar.placeholder': 'Type ang iyong agenda note...',
    'calendar.no_notes': 'Walang notes pa para sa araw na ito.',
    'calendar.more': 'higit pa',
    
    // Reports Page
    'reports.title': 'Mga Ulat at Pagsusuri',
    'reports.subtitle': 'Malawak na mga ulat ng pagdalo at performance analytics',
    'reports.export_csv': 'I-export ang CSV',
    'reports.refresh_data': 'I-refresh ang Data',
    'reports.total_employees': 'Kabuuang mga Empleyado',
    'reports.active_workforce': 'Aktibong workforce',
    'reports.present_today': 'Narito Ngayon',
    'reports.attendance': 'pagdalo',
    'reports.late_today': 'Nahuli Ngayon',
    'reports.need_attention': 'Kailangan ng atensyon',
    'reports.absent_today': 'Wala Ngayon',
    'reports.follow_up_required': 'Kailangan ng follow-up',
    'reports.daily_attendance': 'Daily Attendance Trend',
    'reports.last_7_days': 'Pangkalahatang tanawin ng pagdalo sa huling 7 araw',
    'reports.department_performance': 'Department Performance',
    'reports.attendance_rates': 'Attendance rates ayon sa department',
    'reports.employee_performance': 'Employee Performance Report',
    'reports.detailed_stats': 'Detalyadong mga istatistika ng pagdalo para sa lahat ng mga empleyado',
    'reports.all_employees': 'Lahat ng mga Empleyado',
    'reports.department_summary': 'Department Summary',
    'reports.performance_overview': 'Overview ng performance ayon sa department',
    'reports.total_days': 'Kabuuang mga Araw',
    'reports.attendance_rate': 'Attendance Rate',
    'reports.punctuality_rate': 'Punctuality Rate',
    'reports.error': 'Error',
    'reports.loading_error': 'Nabigo ang pag-load ng reports data',
    'reports.exported': 'Na-export ang Ulat',
    'reports.downloaded': 'Na-download ang attendance report bilang CSV file.',
    
    // Settings Page
    'settings.title': 'Mga Setting ng Sistema',
    'settings.subtitle': 'I-configure ang mga system preferences, integrations, at security settings para sa RAMS',
    'settings.backup_now': 'Mag-backup Ngayon',
    'settings.saving': 'Nagse-save...',
    'settings.save_settings': 'I-save ang mga Setting',
    'settings.system_status': 'Status ng Sistema',
    'settings.database': 'Database',
    'settings.connected': 'Naka-connect',
    'settings.email_service': 'Email Service',
    'settings.active': 'Aktibo',
    'settings.last_backup': 'Last Backup',
    'settings.general_system': 'Mga Pangkalahatang System Settings',
    'settings.general_description': 'I-configure ang mga pangkalahatang system preferences at behavior',
    'settings.email_config': 'Email Configuration',
    'settings.email_description': 'I-configure ang SMTP settings para sa email notifications',
    'settings.test_email': 'I-test ang Email Connection',
    'settings.security_access': 'Security & Access Control',
    'settings.security_description': 'I-configure ang mga security settings at access controls',
    'settings.two_factor': 'Two-Factor Authentication',
    'settings.require_2fa': 'Kailangan ng 2FA para sa mga admin accounts',
    'settings.session_timeout': 'Session Timeout',
    'settings.auto_logout': 'Auto logout pagkatapos ng inactivity',
    'settings.login_attempts': 'Login Attempts',
    'settings.max_failed': 'Max failed login attempts',
    'settings.ip_whitelist': 'IP Whitelist',
    'settings.restrict_access': 'I-restrict ang access sa specific IPs',
    'settings.authorized_users': 'Authorized Users',
    'settings.settings_saved': 'Na-save ang mga Setting',
    'settings.settings_updated': 'Na-update na ang mga system settings ng matagumpay.',
    'settings.connection_test': 'Connection Test',
    'settings.connection_completed': 'na-completed na ang connection test nang matagumpay.',
    'settings.backup_completed': 'Na-complete na ang Backup',
    'settings.backup_created': 'Na-create na ang database backup nang matagumpay.',
    'settings.system': 'Sistema',
    'settings.email': 'Email',
    'settings.security': 'Security',
    'settings.hourly': 'Oras-oras',
    'settings.daily': 'Araw-araw',
    'settings.weekly': 'Lingguhan',
    'settings.monthly': 'Buwanan',
    'settings.minutes': 'minuto',
    'settings.hour': 'oras',
    'settings.hours': 'oras',
    'settings.super_admin': 'Super Admin',
    'settings.admin': 'Admin',
    
    // Users Page
    'users.title': 'Pamamahala ng mga User',
    'users.disabled_notice': 'Ang User Management area na ito ay kasalukuyang disabled.',
    'users.search_users': 'Maghanap ng mga User',
    'users.search_placeholder': 'Maghanap ayon sa pangalan o email...',
    'users.active': 'Aktibo',
    'users.inactive': 'Hindi Aktibo',
    'users.super_admin': 'Super Admin',
    'users.admin': 'Admin',
    'users.viewer': 'Tingnan Lamang',
    
    // Attendance Page
    'attendance.title': 'Pagsusubaybay sa Pagdalo',
    'attendance.subtitle': 'Subaybayan at i-track ang mga attendance logs ng mga empleyado sa real-time',
    'attendance.live_monitoring': 'Live Monitoring',
    'attendance.last_updated': 'Last updated',
    'attendance.refreshing': 'Nagre-refresh...',
    'attendance.refresh_data': 'I-refresh ang Data',
    'attendance.total_employees': 'Kabuuang mga Empleyado',
    'attendance.active_employees': 'Aktibong mga empleyado',
    'attendance.on_time_today': 'On-Time Ngayon',
    'attendance.late_today': 'Nahuli Ngayon',
    'attendance.requires_attention': 'Kailangan ng atensyon',
    'attendance.absent_today': 'Liban Ngayon',
    'attendance.work_not_started': 'Hindi Pa Nagsimula ang Trabaho',
    'attendance.need_followup': 'Kailangan ng follow-up',
    'attendance.logs': 'Attendance Logs',
    'attendance.realtime': 'Real-time na pagsubaybay at pamamahala ng attendance logs',
    'attendance.search_placeholder': 'Maghanap ayon sa pangalan ng empleyado, RFID, o department...',
    'attendance.include_absences': 'Isama ang mga absences',
    'attendance.hide_not_started': 'Itago ang Hindi Pa Nagsimula ang Trabaho',
    'attendance.sort_by': 'Ayusin ayon sa',
    'attendance.direction': 'Direksyon',
    'attendance.ascending': 'Ascending',
    'attendance.descending': 'Descending',
    'attendance.time': 'Oras',
    'attendance.name': 'Pangalan',
    'attendance.employee': 'Empleyado',
    'attendance.school_id': 'School ID',
    'attendance.department': 'Department',
    'attendance.log_type': 'Uri ng Log',
    'attendance.date': 'Petsa',
    'attendance.status': 'Status',
    'attendance.notes': 'Mga Notes',
    'attendance.all_statuses': 'Lahat ng mga Status',
    'attendance.all_types': 'Lahat ng mga Uri',
    'attendance.all_staff': 'Lahat ng mga Staff',
    'attendance.teaching': 'Teaching',
    'attendance.non_teaching': 'Non-Teaching',
    'attendance.no_logs': 'Walang nakitang attendance logs. Lilitaw ang mga logs dito kapag gumamit ng kanilang RFID cards ang mga empleyado.',
    'attendance.no_match': 'Walang logs na tumugma sa iyong kasalukuyang mga filter.',
    'attendance.page_of': 'Page',
    'attendance.of': 'of',
    'attendance.prev': 'Prev',
    'attendance.next': 'Next',
    'attendance.pick_date': 'Pumili ng petsa',
    'attendance.today': 'Ngayon',
    'attendance.on_time': 'On-Time',
    'attendance.late': 'Nahuli',
    'attendance.absent': 'Liban',
    'attendance.data_updated': 'Na-update ang Data',
    'attendance.loaded_logs': 'Matagumpay na na-load',
    'attendance.attendance_logs': 'attendance logs',
    'attendance.error': 'Error',
    'attendance.load_failed': 'Nabigo ang pag-load ng attendance data',
    'attendance.unknown_employee': 'Hindi Kilalang Empleyado',
    'attendance.na': 'Wala',
    'attendance.logs_word': 'mga tala',
    
    // Employees Page
    'employees.title': 'Pamamahala ng mga Empleyado',
    'employees.subtitle': 'Pamahalaan ang lahat ng faculty members at non-teaching staff sa STI College Santa Rosa',
    'employees.add_employee': 'Magdagdag ng Empleyado',
    'employees.total_employees': 'Kabuuang mga Empleyado',
    'employees.registered_employees': 'Mga rehistradong empleyado',
    'employees.departments': 'Mga Department',
    'employees.across_departments': 'Sa iba\'t ibang mga department',
    'employees.filter_search': 'I-filter at Maghanap ng mga Empleyado',
    'employees.search_placeholder': 'Maghanap ayon sa pangalan, ID, email, o RFID code...',
    'employees.all_departments': 'Lahat ng mga Department',
    'employees.all_statuses': 'Lahat ng mga Status',
    'employees.employee_directory': 'Direktoryo ng mga Empleyado',
    'employees.showing': 'Nagpapakita ng',
    'employees.of': 'sa',
    'employees.employees': 'mga empleyado',
    'employees.name': 'Pangalan',
    'employees.department_position': 'Department / Position',
    'employees.contact': 'Kontak',
    'employees.rfid_schedule': 'RFID / Schedule',
    'employees.status': 'Status',
    'employees.work_status': 'Work Status',
    'employees.actions': 'Mga Aksyon',
    'employees.view': 'Tingnan',
    'employees.edit': 'I-edit',
    'employees.delete': 'Tanggalin',
    'employees.active': 'Aktibo',
    'employees.inactive': 'Hindi Aktibo',
    'employees.regular': 'Regular',
    'employees.part_time': 'Part Time',
    'employees.part_time_full_load': 'Part Time Full Load',
    'employees.teaching': 'Teaching',
    'employees.non_teaching': 'Non-Teaching',
    
    // Verification Page
    'verification.title': 'Mga Hiling sa Pagpapatunay',
    'verification.subtitle': 'Suriin at pamahalaan ang mga hiling sa pagpapatunay ng mga empleyado',
    'verification.pending': 'Nakabinbin',
    'verification.approved': 'Naaprubahan',
    'verification.rejected': 'Natanggi',
    'verification.all_statuses': 'Lahat ng mga Status',
    'verification.search_placeholder': 'Maghanap ayon sa pangalan ng empleyado o ID...',
    'verification.employee': 'Empleyado',
    'verification.request_type': 'Uri ng Hiling',
    'verification.date_requested': 'Petsa ng Hiling',
    'verification.status': 'Status',
    'verification.actions': 'Mga Aksyon',
    'verification.approve': 'Aprubahan',
    'verification.reject': 'Tanggihan',
    'verification.view_details': 'Tingnan ang mga Detalye',
    'verification.no_requests': 'Walang nakitang mga hiling sa pagpapatunay',
    'verification.filter_by_status': 'I-filter ayon sa Status',
    
    // Audit Trail Page
    'audit.title': 'Tala ng Audit',
    'audit.subtitle': 'Subaybayan ang lahat ng mga gawain at pagbabago sa sistema',
    'audit.search_placeholder': 'Maghanap ayon sa user, aksyon, o paglalarawan...',
    'audit.filter_by_action': 'I-filter ayon sa Aksyon',
    'audit.all_actions': 'Lahat ng mga Aksyon',
    'audit.user': 'User',
    'audit.action': 'Aksyon',
    'audit.description': 'Paglalarawan',
    'audit.timestamp': 'Timestamp',
    'audit.details': 'Mga Detalye',
    'audit.view_details': 'Tingnan ang mga Detalye',
    'audit.no_logs': 'Walang nakitang log trail entries',
    'audit.clear_logs': 'Linisin ang Log Trail',
    'audit.export_logs': 'I-export ang mga Logs',
    'audit.refresh': 'I-refresh',
  }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')
  const [isClient, setIsClient] = useState(false)

  // Ensure we're on the client side
  useEffect(() => {
    setIsClient(true)
  }, [])

  // Load language preference from localStorage on mount (client-side only)
  useEffect(() => {
    if (!isClient) return
    
    try {
      const savedLanguage = localStorage.getItem('rams_language') as Language
      if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'fil')) {
        setLanguage(savedLanguage)
      }
    } catch (error) {
      console.warn('Failed to load language preference:', error)
    }
  }, [isClient])

  // Save language preference to localStorage when it changes (client-side only)
  useEffect(() => {
    if (!isClient) return
    
    try {
      localStorage.setItem('rams_language', language)
    } catch (error) {
      console.warn('Failed to save language preference:', error)
    }
  }, [language, isClient])

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
